version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build/

#permissions:
#  - object: /
#    pattern: "**"
#    onwer: ec2-user
#    onwer: ec2-user

files:
  - source: target/demo-0.0.1-SNAPSHOT.war
    destination: /usr/share/tomcat7/webapps/

hooks:
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
