version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build/

#files:
#  - source: target/*.war
#    destination: /usr/share/tomcat7/webapps/
#    overwrite: yes

hooks:
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
