version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build/

permissions:
  - object: /
    pattern: "**"
    onwer: ec2-user
    onwer: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
